site_name: Haocheng Yang - Game Developer
site_url: https://howchen217.github.io/haochengyang-portfolio/
nav:
  - Home: index.md
  - Projects:
    - Unreal: 
      - Scouts Odyssey: projects/scoutsodyssey.md
      - Afterville: projects/afterville.md
    - Unity: 
      - Lion Dancer: projects/liondancer.md
      - Mall Cop: projects/mallcop.md
      - Kamukchi: projects/kamukchi.md
      - Dial B for Bee: projects/dialbforbee.md
      - A for Aletta: projects/aforaletta.md
    - XR:
      - Therapet: projects/therapet.md
  - Devlogs:
    - devlogs/immersivesimsautonomy.md
    - devlogs/crusaderkingsmodders.md
    - devlogs/creatingfeints.md
  - Contact: contact.md

theme:
  favicon: img/favicon.ico
  logo: img/HaochengIcon.png
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: indigo
      accent: indigo 
    - scheme: default 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: indigo
      accent: lime

extra_css:
  - css/style.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: google.com
    - icon: fontawesome/brands/linkedin
      link: google.com
    - icon: fontawesome/brands/youtube
      link: google.com

plugins:
    - mkdocs-video:
        css_style:
          align: “left”
        is_video: True
        video_type: webm
        video_autoplay: True
        video_loop: True
        video_muted: True
        video_controls: False

copyright: Copyright &copy; 2023 Haocheng Yang